"""movimentacao_attachments

Revision ID: 344038d20cd5
Revises: 003
Create Date: 2026-04-05 20:54:35.306133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '344038d20cd5'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mov_attachments_movimentacao', 'movimentacao_attachments', ['movimentacao_id', 'is_deleted'], unique=False)
    op.create_index('idx_mov_attachments_team', 'movimentacao_attachments', ['team_id'], unique=False)
    op.drop_index(op.f('idx_pag_attachments_pagamento'), table_name='pagamento_attachments')
    op.drop_index(op.f('idx_pag_attachments_team'), table_name='pagamento_attachments')
    op.drop_table('pagamento_attachments')
    op.drop_column('diarias', 'updated_at')
    op.drop_column('diarists', 'updated_at')
    op.drop_column('images', 'updated_at')
    op.drop_column('item_attachments', 'updated_at')
    op.drop_column('items', 'updated_at')
    op.drop_column('movimentacoes', 'updated_at')
    op.drop_column('mural_attachments', 'updated_at')
    op.drop_column('mural_posts', 'updated_at')
    op.drop_column('obras', 'updated_at')
    op.drop_column('pagamentos_agendados', 'updated_at')
    op.drop_column('solicitacoes_cadastro', 'updated_at')
    op.drop_index(op.f('idx_teams_cnpj'), table_name='teams')
    op.drop_constraint(op.f('uq_teams_cnpj'), 'teams', type_='unique')
    op.create_index(op.f('ix_teams_cnpj'), 'teams', ['cnpj'], unique=True)
    op.drop_column('teams', 'updated_at')
    op.drop_index(op.f('idx_users_cpf'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('uq_users_cpf'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_cpf'), 'users', ['cpf'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_cpf'), 'users', ['cpf'], unique=False)
    op.add_column('teams', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_teams_cnpj'), table_name='teams')
    op.create_unique_constraint(op.f('uq_teams_cnpj'), 'teams', ['cnpj'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_teams_cnpj'), 'teams', ['cnpj'], unique=False)
    op.add_column('solicitacoes_cadastro', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('pagamentos_agendados', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('obras', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('mural_posts', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('mural_attachments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('movimentacoes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('item_attachments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('diarists', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('diarias', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table('pagamento_attachments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pagamento_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos_agendados.id'], name=op.f('pagamento_attachments_pagamento_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('pagamento_attachments_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pagamento_attachments_pkey'))
    )
    op.create_index(op.f('idx_pag_attachments_team'), 'pagamento_attachments', ['team_id'], unique=False)
    op.create_index(op.f('idx_pag_attachments_pagamento'), 'pagamento_attachments', ['pagamento_id', 'is_deleted'], unique=False)
    op.drop_index('idx_mov_attachments_team', table_name='movimentacao_attachments')
    op.drop_index('idx_mov_attachments_movimentacao', table_name='movimentacao_attachments')
    op.drop_table('movimentacao_attachments')
    # ### end Alembic commands ###
